### ISSUE TITLE
printRow issues

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-checkuhs#15]
https://github.com/TU-CSCI2322-FL22/solver-checkuhs/blob/0511d85d8e36197dc268fb9b5c7855e41c001161/Checkers.hs#L50-L56

Bigger issue: you can't assume that the board and list of locations will be in lockstep. Instead, use `lookup`.

Minor issue: pattern match instead of fst/send (usually)
```haskell
 printRow :: Board -> [Loc] -> String 
 printRow _ [] = "" 
 printRow [] (p:ps) = "_ " ++ printRow [] ps 
 printRow (b@(loc,piece):bs) (p:ps) =  
     if (loc == p) then show (fst piece)++ " " ++ printRow bs ps 
     else if (snd loc /= snd p) then "_ " ++ printRow bs ps 
     else "_ " ++ printRow (b:bs) ps 
```

Wontfix issue: it is better to decompose "vertically" (i.e. `printCell :: Board -> Loc -> String`) than horizontally (doing both the recursion and the location-checking-and-converting-into-string at the same time).

**Comment by SStepanik** [comment]
LookUp was utilized
