### ISSUE TITLE
This could be more abstract

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-checkuhs#19]
https://github.com/TU-CSCI2322-FL22/solver-checkuhs/blob/0511d85d8e36197dc268fb9b5c7855e41c001161/Checkers.hs#L36-L40

Instead of having to remember the details, you could functionify this
```haskell
shouldKingify :: Color -> Loc -> Bool
shouldKingify Red loc = loc `elem` [(1,0),(3,0),(5,0),(7,0)] 
shouldKingify Black loc = loc `elem` [(0,7),(2,7),(4,7),(6,7)] 
```

**Comment by KinseyNeas** [comment]
Implemented this note.
