### ISSUE TITLE
This zip is unsafe!

### ISSUE THREAD

**Issue by sfogarty** [TU-CSCI2322-FL22/solver-checkuhs#35]
You might have dropped some game states with the `catMaybe`s! You should create tuples from the very beginning, probably with list comprehensions. 

https://github.com/TU-CSCI2322-FL22/solver-checkuhs/blob/bc1560e3f27bd31a61254ea93e1c1a0bfb12928b/Solver.hs#L35

**Comment by KinseyNeas** [comment]
We fixed it!
